=== Michael2601/PDaPL/files/practice8/in/railwayXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Railway" type="RailwayType">
        <xs:annotation>
            <xs:documentation>
                Top-level element holding a collection of Depots elements.
            </xs:documentation>
        </xs:annotation>
        <xs:unique name="UniqueIdKey">
            <xs:selector xpath=".//Depot/Train/CompositionElement/Employee"/>
            <xs:field xpath="Id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="RailwayType">
        <xs:sequence>
            <xs:element name="Depot" type="DepotType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepotType">
        <xs:sequence>
            <xs:element name="DepotNumber" type="xs:int"/>
            <xs:element name="Train" type="TrainType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TrainType">
        <xs:sequence>
            <xs:element name="TrainName" type="xs:string"/>
            <xs:element name="CompositionElement" type="CompositionType" minOccurs="1" maxOccurs="30"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CompositionType">
        <xs:sequence>
            <xs:element name="CompositionElementName" type="xs:string"/>
            <xs:element name="Employee" type="EmployeeType" minOccurs="2" maxOccurs="10"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="Id" type="idType" minOccurs="1" maxOccurs="1">

            </xs:element>
            <xs:element name="Gender" type="genderType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="FirstName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="LastName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="MiddleName" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="EmployeeRole" type="roleType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="genderType">
        <xs:restriction base="xs:string">
            <xs:pattern value="male|female"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Driver"/>
            <xs:enumeration value="Assistant driver"/>
            <xs:enumeration value="Main conductor"/>
            <xs:enumeration value="Conductor"/>
            <xs:enumeration value="Assistant conductor"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idType">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Michael2601/PDaPL/files/practice8/in/railway.xml
<?xml version="1.0" encoding="UTF-8"?>
<Railway xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="railwayXSD.xsd">
    <Depot>
        <DepotNumber>1</DepotNumber>
        <Train>
            <TrainName>Stork 1</TrainName>
            <CompositionElement>
                <CompositionElementName>Locomotive</CompositionElementName>
                <Employee>
                    <Id>000001</Id>
                    <Gender>male</Gender>
                    <FirstName>Test1</FirstName>
                    <LastName>Test1</LastName>
                    <MiddleName>Test1</MiddleName>
                    <EmployeeRole>Driver</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000002</Id>
                    <Gender>male</Gender>
                    <FirstName>Test2</FirstName>
                    <LastName>Test2</LastName>
                    <MiddleName>Test2</MiddleName>
                    <EmployeeRole>Assistant driver</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000003</Id>
                    <Gender>male</Gender>
                    <FirstName>Test3</FirstName>
                    <LastName>Test3</LastName>
                    <MiddleName>Test3</MiddleName>
                    <EmployeeRole>Main conductor</EmployeeRole>
                </Employee>
            </CompositionElement>
            <CompositionElement>
                <CompositionElementName>Carriage 1</CompositionElementName>
                <Employee>
                    <Id>000004</Id>
                    <Gender>female</Gender>
                    <FirstName>Test4</FirstName>
                    <LastName>Test4</LastName>
                    <MiddleName>Test4</MiddleName>
                    <EmployeeRole>Conductor</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000005</Id>
                    <Gender>female</Gender>
                    <FirstName>Test5</FirstName>
                    <LastName>Test5</LastName>
                    <MiddleName>Test5</MiddleName>
                    <EmployeeRole>Assistant conductor</EmployeeRole>
                </Employee>
            </CompositionElement>
        </Train>
        <Train>
            <TrainName>Stork 2</TrainName>
            <CompositionElement>
                <CompositionElementName>Locomotive</CompositionElementName>
                <Employee>
                    <Id>000006</Id>
                    <Gender>male</Gender>
                    <FirstName>Test6</FirstName>
                    <LastName>Test6</LastName>
                    <MiddleName>Test6</MiddleName>
                    <EmployeeRole>Driver</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000007</Id>
                    <Gender>male</Gender>
                    <FirstName>Test7</FirstName>
                    <LastName>Test7</LastName>
                    <MiddleName>Test7</MiddleName>
                    <EmployeeRole>Assistant driver</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000008</Id>
                    <Gender>male</Gender>
                    <FirstName>Test8</FirstName>
                    <LastName>Test8</LastName>
                    <MiddleName>Test8</MiddleName>
                    <EmployeeRole>Main conductor</EmployeeRole>
                </Employee>
            </CompositionElement>
            <CompositionElement>
                <CompositionElementName>Carriage 1</CompositionElementName>
                <Employee>
                    <Id>000009</Id>
                    <Gender>female</Gender>
                    <FirstName>Test9</FirstName>
                    <LastName>Test9</LastName>
                    <MiddleName>Test9</MiddleName>
                    <EmployeeRole>Conductor</EmployeeRole>
                </Employee>
                <Employee>
                    <Id>000010</Id>
                    <Gender>female</Gender>
                    <FirstName>Test10</FirstName>
                    <LastName>Test10</LastName>
                    <MiddleName>Test10</MiddleName>
                    <EmployeeRole>Assistant conductor</EmployeeRole>
                </Employee>
            </CompositionElement>
        </Train>
    </Depot>
</Railway>
